<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function getByFirstNameLike($firstName)
	{
		return $this->createQueryBuilder('u')
			->where('u.firstName LIKE %:name%')
			->setParameter('name', $firstName)
			->getQuery()
			->getResult();
	}
}
